name: build an push image
on: 
  push:
    branches:
      - 'main'

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push:
    name: Build and push GAR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: nada
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # Provided as Organization Secret
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }} # Provided as Organization Variable
