name: build an push image
on: 
  push:
    branches:
      - 'main'

permissions:
  contents: read
  packages: write

jobs:
  set-version:
    name: Set version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: set version
        id: set-version
        run: echo ::set-output name=version::"$(date '+%Y-%m-%d')-$(git --no-pager log -1 --pretty=%h)"
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-20.04
    needs: set-version
    steps:
    - uses: actions/checkout@v4
    - name: Set up environment
      run: |
        version=${{ needs.set-version.outputs.version }}
        prefix=ghcr.io/${{ github.repository }}
        echo "IMAGE=$prefix:$version" >> $GITHUB_ENV
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Dockerimage
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE }}
