name: build and push image
on: 
  push:
    branches:
      - 'main'

permissions:
  contents: write
  id-token: write

jobs:
  build-and-push:
    name: Build and push GAR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: nada
      - name: Create release
        uses: ncipollo/release-action@v1
        with: 
          name: ${{ steps.docker-build-push.outputs.tag }}
          makeLatest: true
          tag: ${{ steps.docker-build-push.outputs.tag }}
