name: build and push image
on: 
  push:
    branches:
      - 'main'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: nada
      - name: Login to GitHub Container Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # Use commit-sha1 instead of tag for security concerns
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.docker-build-push.outputs.tag }}
      - name: Create release
        uses: ncipollo/release-action@v1
        with: 
          name: ${{ steps.docker-build-push.outputs.tag }}
          makeLatest: true
          tag: ${{ steps.docker-build-push.outputs.tag }}
